### ISSUE TITLE
Custom domains don't work anymore as it uses a legacy feature

### ISSUE THREAD

**Issue by JackBailey** [IvanArjona/cloudflare-tunnel-vscode#5]
Set a custom domain in settings.json and running into this error

`Initiating shutdown error="you are using Cloudflare Tunnel in a (legacy) way that is no longer supported.Migrate to Named Tunnels to continue exposing your private origin through Cloudflare's Network.You can follow this guide: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/do-more-with-tunnels/migrate-legacy-tunnels as an example.Alternatively, you can go to https://dash.teams.cloudflare.com/ -> Access -> Tunnels -> Create and rely on the User Interface instead."`

**Comment by IvanArjona** [comment]
Fixed in c1f01e5ed1a0a035f6344f63dfe109dc7edfba44
