### ISSUE TITLE
Receiving error when trying to start a tunnel

### ISSUE THREAD

**Issue by wildernessfamily** [IvanArjona/cloudflare-tunnel-vscode#7]
Hi, I'm receiving this error when trying to start a tunnel: `Error: spawn Unknown system error -8`
I choose CloudFlare login. It states I'm logged in.
I have tried a few different ways regarding the subdomain. I made up a subdomain. Same error. I configured the subdomain in ZeroTrust and still same error. 
I looked for a spot to enter my API key but could find it. When I choose CloudFlare login it just gives a popup stating I'm logged in. But never redirects me to a browser log-in page of CloudFlare or for my API key.
I've also tried logging out and back in too.
Extension version: v0.3.4
System: MacBookPro Version 12.6.8
VSCode: Version: 1.81.1 (Universal)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 21.6.0

**Comment by giosad** [comment]
It just doesn't support macOs -- see [here](https://github.com/IvanArjona/cloudflare-tunnel-vscode/blob/32d55a9bc8e59242fff68c0380effc71c28ea733/src/downloader.ts#L21). It downloads just Windows / Linux binaries.

**Comment by wildernessfamily** [comment]
Ahhh, well that sucks :) But...since I wrote this, I moved over to Windows11. I'll give it a try now.
Thanks for taking the time to look into this.
